apps/pokes/urls.py
from django.conf.urls import url, include
from . import views 

urlpatterns = [
    url(r'^(?P<receiver_id>\d+)/poke$', views.poke, name="poke")
]

apps/users/urls.py
from django.conf.urls import url, include
from . import views 

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.new, name="new"),
    url(r'^create/$', views.create, name="create"),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout')
]

poke_exam_2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.users.urls', namespace='users')),
    url(r'^pokes/', include('apps.pokes.urls', namespace='pokes'))
]

apps/pokes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect, HttpResponse

from django.db import models
from datetime import datetime

import bcrypt
import re
# from ..users.models import User

class PokeManager(models.Manager):
    def add_poke(self, receiver_id):
        try:
            receiver = User.objects.get(id=receiver_id)
            receiver.poked_number += 1
            receiver.save()
            return True
        except:
            return False
    
    def create_poke(self, receiver_id, giver_id):
        giver = User.objects.get(id=giver_id)
        
        try:
            poke = self.create(
                giver=giver.name,
                receiver=User.objects.get(id=receiver_id)
            )

            return True
        except:
            return HttpResponse('poke was not created')
            
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def validate_and_create_user(self, form_data):
        errors = []

        if len(form_data['name']) < 3:
            errors.append(['funny name, ', form_data['name'], '!'])
        if len(form_data['alias']) < 3:
            errors.append([form_data['alias'], " ,that's what you call yourself!?"])
        if not EMAIL_REGEX.match(form_data['email']):
            errors.append('Must use a valid email address')
        if len(form_data['password']) < 3:
            errors.append("that ain't a password!")
        if not form_data['dob']:
            errors.append('you are not one of us, get out!') 
        if form_data['password'] != form_data['confirm']:
            errors.append("Only one password per person, that's the rule")
        if errors:
            return (False, errors)

        try:
            existing_user = self.get(email=form_data['email'])
            errors.append('User already exists.')
            return (False, errors)
        except:
            pw_hash = bcrypt.hashpw(form_data['password'].encode(), bcrypt.gensalt())
            dob = datetime.strptime(form_data['dob'],  '%Y-%m-%d').date()
            user = self.create(
                name=form_data['name'], 
                alias=form_data['alias'],
                email=form_data['email'],
                dob=dob,
                pw_hash=pw_hash
            )
            return (True, user.id)
        
    def login_user(self, form_data):
        errors = []
        try:
            user = self.get(email=form_data['email'])
            if not bcrypt.checkpw(form_data['password'].encode(), user.pw_hash.encode()):
                errors.append('password is invalid')
                return (False, errors)
            return (True, user.id)
        except:
            errors.append('email  is invalid')
            return (False, errors)

class User(models.Model):
    name = models.CharField(max_length=100)
    alias = models.CharField(max_length=100)
    email = models.CharField(max_length=255)
    dob = models.DateField()
    poked_number = models.IntegerField(default=0)
    pw_hash = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    last_mod = models.DateTimeField(auto_now=True)
    objects = UserManager()

# one to many: each poke is created by one person, one person can create many pokes
# giver is name of person who created poke
# receiver is foreign key, person who was poked
 
class Poke(models.Model):
    giver = models.CharField(max_length=100)
    receiver = models.ForeignKey(User, related_name='users')
    objects = PokeManager()

def __str__(self):
    return self.id

apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from datetime import datetime

import bcrypt
import re

from ..pokes.models import Poke


# def __str__(self):
#     return self.id

apps/pokes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, HttpResponse
from .models import Poke, User


# receiver_id refers to the id of a person listed (receiver), not the logged in user
def poke(req, receiver_id):
    valid = Poke.objects.add_poke(receiver_id)
    if not valid:
        return HttpResponse('poke was not added')
    giver_id = req.session['user_id']
    valid = Poke.objects.create_poke(receiver_id, giver_id)
    
    if not valid:
        return HttpResponse('model couldnt find receciver')
    
    return redirect('users:index')

apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ..pokes.models import User, Poke
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages


def index(req):
  if 'user_id' not in req.session:
    return redirect('users:new')

  user_id = req.session['user_id']
  pokers = Poke.objects.filter(receiver__in=User.objects.filter(id=user_id).order_by('poked_number'))
  # grouped_pokers =Poke.objects.raw(
  #                                 SELECT COUNT(
  #                                         SELECT * from Poke
  #                                         WHERE receiver = logged_in_user)
  #                                 GROUP BY poker)
  context = {
    'user': User.objects.get(id=user_id),
    'count': pokers.count(),
    'all': User.objects.exclude(id=user_id),
    'pokes': User.objects.filter(id=user_id).filter(users__in=Poke.objects.all()),
    'pokers': pokers
  }
  return render(req, 'users/index.html', context)

def new(req):
  return render(req, 'users/new.html')

def create(req):
  if req.method != 'POST':
    return redirect('users:new')

  valid, result = User.objects.validate_and_create_user(req.POST)
  if not valid:
    for err in result:
      messages.error(req, err)
    return redirect('users:new')

  req.session['user_id'] = result
  return redirect('users:index')

def login(req):
  if req.method != "POST":
    return redirect('users:new')

  valid, result = User.objects.login_user(req.POST)
  print "*"*30
  print result
  if not valid:
    for err in result:
      messages.error(req, err)
    return redirect('users:new')

  req.session['user_id'] = result
  return redirect('users:index')

def logout(req):
  req.session.clear()
  return redirect('users:index')

apps/users/templates/users/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <script src="main.js"></script>
</head>

<body>
    <!-- {{request.session.user_id}} -->
    <a href="{% url 'users:logout' %}" class="button">Logout</a>

    <h1>welcome {{user.name}}</h1>
    {% if count %}
        <h2>{{ count }} poeple have poked you</h2>
        <hr>
        <h3>People who poked you!</h3>
        {% for poke in pokers %}
            <ul>
                <li> {{ poke.giver }} poked you {{ poke.poked_number }} many times.</li>
            </ul>
        {% endfor %}
    {% endif %}
    

    <hr>
    <!-- <h2>{{ all }}</h2> -->
    <hr>
    <h3>People you may want to poke</h3>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Alias</th>
                <th>Email</th>
                <th>Poke History</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for user in all %}
            <tr>
                <td>{{ user.name }}</td>
                <td>{{ user.alias }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.poked_number }}</td>
                <td>
                    <a href="{% url 'pokes:poke' receiver_id=user.id %}" class="button">Poke</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


</body>

</html>

apps/users/templates/users/new.html
<!DOCTYPE html>
<html>

<head>
    <title>user Index</title>
</head>

<body>
    {{request.session.user_id}}
    <h2>welcome</h2>
    <br> {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}
    <h3>create an account or log in</h3>
    <hr>
    <form action="{% url 'users:create' %}" method="post">
        {% csrf_token %}
        <label for="name">Name</label>
        <br>
        <input type="text" name="name" placeholder="Sponge Bob">
        <br>
        <label for="user_name">Alias</label>
        <br>
        <input type="text" name="alias" placeholder="Bob Sponge">
        <br>
        <label for="email">Email</label>
        <br>
        <input type="text" name="email" placeholder="cool@stuff.go">
        <br>
        <label for="password">password</label>
        <br>
        <input type="password" name="password" placeholder="your darkest secret ......">
        <br>
        <label for="confirm">confirm password</label>
        <br>
        <input type="password" name="confirm" placeholder="rubSomeBaconOnIt">
        <br>
        <label for="dob">Date od Birth</label>
        <br>
        <input type="date" name="dob">
        <br>
        <input type="submit" value="Register">
    </form>
    <br>
    <h3>New User form</h3>
    <hr>
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <label for="email">Email</label>
        <br>
        <input type="text" name="email">
        <br>
        <label for="password">password</label>
        <br>
        <input type="password" name="password">
        <br>
        <input type="submit" value="Login">
    </form>


</body>

</html>